### Get all contacts
GET http://localhost:8080/contacts
Content-Type: application/json

### Get a single contact by ID
GET http://localhost:8080/contacts/68cf1f4b902557563a2b98d8
Content-Type: application/json

### Get all contacts (Render)
GET https://https://cse341-oe9i.onrender.com/contacts
Content-Type: application/json

### Get a single contact by ID (Render)
GET https://https://cse341-oe9i.onrender.com/contacts/68cf1f4b902557563a2b98d8
Content-Type: application/json
